---
# Update a user password
# Requires user_name as an extra var
# example --extra-vars="user_name=vagrant"

- hosts: all
  name: set user password
  become: "{{ use_sudo | default(true) }}"
  gather_facts: False
  roles:
    - password
